package plausibcheck.car

import com.neo.drools.model.Car;
import com.alibaba.fastjson.JSON;


rule "piece"
    when
        car : Car(piece > 4 &&  piece < 70)
    then
        System.out.println(JSON.toJSONString(car));
        Integer price=car.getPrice()-car.getPiece()*2;
        car.setLastPrice(car.getLastPrice()>price?price:car.getLastPrice());
		System.out.println("piece规则");
end

rule "price"
    when
        car : Car(price > 100 && price < 920 )
    then
        System.out.println(JSON.toJSONString(car));
        Integer price=car.getPrice()-car.getPrice()/2;
        car.setLastPrice(car.getLastPrice()>price?price:car.getLastPrice());
		System.out.println("price规则");
end

rule "score 100-200积分"
    when
        car : Car(score > 100 && score < 200 )
    then
    System.out.println(JSON.toJSONString(car));
        Integer price=car.getPrice()-car.getScore()/5-20;
        car.setLastPrice(car.getLastPrice()>price?price:car.getLastPrice());
		System.out.println("score 100-200积分规则");
end

rule "score 200-300积分"
    when
        car : Car(score > 200 && score < 300 )
    then
    System.out.println(JSON.toJSONString(car));
        Integer price=car.getPrice()-car.getScore()/5-30;
        car.setLastPrice(car.getLastPrice()>price?price:car.getLastPrice());
		System.out.println("score 200-300积分规则");
end